FileVersion = 1

[Project]
Name = "minicoro-beef"
TargetType = "BeefLib"
StartupObject = "minicoro_beef.Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\minicoro_d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\minicoro.lib"]
